#!/bin/bash

EMAIL=jrblevin@sdf.org
HOSTNAME=$(hostname)
EXCLUDE_IP="192\.168\.1\.\\|128\.146\.137\.52\\|140\.254\.\\|207\.254\.73\.13\\|75\.118\."
EXCLUDE_HOST="econ.ohio-state.edu\\|osuwireless.ohio-state.edu\\|col\.wideopenwest\.com\\|myvzw.com\\|dsl.wotnoh.sbcglobal.net\\|insight.res.rr.com\\|central.biz.rr.com"

imap_login() {
    FILE=/var/log/mail.info
    test -f $FILE && cat $FILE | \
        grep imap-login | \
        grep rip= | \
        sed -n 's/.*rip=\(.*\), lip=.*/\1/p'
}

smtp_auth() {
    FILE=/var/log/exim/mainlog
    test -f $FILE && cat $FILE | \
        grep -E "P=esmtps?a" | \
        sed -n 's/.*[\(.*\)] P=esmtp.*/\1/p'
}

sshd() {
    FILE=/var/log/auth.log
    test -f $FILE && cat $FILE | \
        grep -E 'sshd.*Accepted.*from' | \
        sed -n 's/.*from \(.*\) port.*/\1/p'
}

all_ips() {
    sshd
    imap_login
    smtp_auth
}

lookup() {
    LOOKUP_RES=$(nslookup -timeout=30 $1 | sed -n 's/.*arpa.*name = \(.*\)\./\1/p')
    test -z "$LOOKUP_RES" && LOOKUP_RES="Failed"
    echo -e "$1\t$LOOKUP_RES"
}

lookup_all () {
    for IP in $(all_ips | grep -v "$EXCLUDE_IP" | sort | uniq); do
        lookup $IP;
    done
}

MESSAGE=$(lookup_all | grep -v "$EXCLUDE_HOST")
if [ -n "$MESSAGE" ]; then
  echo $MESSAGE | mail -s "Access List for $HOSTNAME" $EMAIL
fi
