#!/bin/sh

imap_login() {
    FILE=/var/log/mail.info
    test -f $FILE && cat $FILE | \
        grep imap-login | \
        grep rip= | \
        sed -n 's/.*rip=\(.*\), lip=.*/\1/p'
}

smtp_auth() {
    FILE=/var/log/exim/mainlog
    test -f $FILE && cat $FILE | \
        grep -E "P=esmtps?a" | \
        sed -n 's/.*[\(.*\)] P=esmtp.*/\1/p'
}

sshd() {
    FILE=/var/log/auth.log
    test -f $FILE && cat $FILE | \
        grep -E 'sshd.*Accepted.*from' | \
        sed -n 's/.*from \(.*\) port.*/\1/p'
}

all_ips() {
    sshd
    imap_login
    smtp_auth
}

lookup() {
    LOOKUP_RES=$(nslookup -timeout=10 $1 | sed -n 's/.*arpa.*name = \(.*\)\./\1/p')
    test -z "$LOOKUP_RES" && LOOKUP_RES="Failed"
    echo "$1\t$LOOKUP_RES"
}

for IP in $(all_ips | sort | uniq); do
    lookup $IP;
done
