#!/bin/bash

# rsync backup script
#
# Copyright (C) 2008-2016 Jason Blevins <jrblevin@sdf.org>
#
# Usage: backup host path
#
# Backups for $HOST are stored in the directory $BASE/$HOST where
# $BASE is hard-coded below.  This script keeps the last 12 monthly
# snapshots, four weekly snapshots, and seven daily snapshots.
#
# See also: http://www.sanitarium.net/golug/rsync_backups.html

# Location of backup files
BASE=/backup

# Excluded files (e.g., extremely large files that change often)
# Example: --exclude pattern1 --exclude pattern2
EXCLUDE="--exclude .sync --exclude .dropbox.cache --exclude .dropbox --exclude .dropbox-dist"

RSYNC=/usr/bin/rsync
REMOTE_RSYNC=/usr/local/bin/rsync
RSYNC_OPTS="-avHAXx --numeric-ids --delete $EXCLUDE --rsync-path $REMOTE_RSYNC"
#RSYNC_OPTS="-n -avHx --delete $EXCLUDE"
SSH=/usr/bin/ssh
SELF=$(hostname)

snapshot() {
    host=$1
    path=$2
    name=$3

    echo "===== $host:$path ====="

    # Use rsync to update the current copy
    if [[ "$host" == "$SELF" ]]; then
        # local backup
        $RSYNC $RSYNC_OPTS $path/ $name-current/
    else
        # remote backup via SSH
        $RSYNC $RSYNC_OPTS -e $SSH $host:$path/ $name-current/
    fi

    # Create a snapshot tree of hard links
    cp -al $name-current $name-`date +"%Y-%m-%d"`
}


rotate() {
    host=$1
    path=$2
    name=$3

    if [[ "`date +%A`" == "Sunday" ]]; then
        # Delete the weekly backup from four weeks ago unless it was the
        # first sunday of the month.  If so, keep it as a monthly backup.
        if [[ `date --date="-4 week" +"%d"` -gt 7 ]]; then
            ymd=$(date --date="-4 week" +%Y-%m-%d)
            echo "Deleting $ymd weekly $host:$path snapshot..."
            rm -rf $name-$ymd
        fi

        # Delete the monthly backup from 12 months ago.
        echo "Deleting $(date --date="-1 year" +"%B %Y") monthly $host:$path snapshot..."
        rm -rf $name-`date --date="-1 year" +"%Y-%m-%d"`
    else
        # Delete the daily snapshot from a week ago.
        ymd=$(date --date="-1 week" +%Y-%m-%d)
        echo "Deleting $ymd daily $host:$path snapshot..."
        rm -rf $name-$ymd
    fi
}


# Store the hostname and path
host=$1
path=$2

# replace slashes with underscores
name=${path//\//_}

# Change to the archive directory (make it if needed)
mkdir -p $BASE/$host
cd $BASE/$host

# Archive a snapshot the path and rotate old snapshots
snapshot $host $path $name
rotate $host $path $name
