#!/bin/bash
#
# Copyright (C) 2010 Jason R. Blevins
# License: 3-clause BSD
#
# Stores bookmarks, with titles, tags, and descriptions, in a
# tab-delimited text file with format:
#
# [1:time] [2:url] [3:tags] [4:title] [5:description]

FILE=$HOME/config/app/bookmarks.txt
OUTPUT=$HOME/projects/jblevins.org/links/assorted.text

usage() {
    echo "Usage:"
    echo "  bm add URL"
    echo "  bm edit"
    echo "  bm search <pattern>"
    echo "  bm publish"
    echo
    exit 1
}

add() {
    time=$(date +%s)
    url=$1

    echo "Fetching $url..."
    title=$( wget -q -O - "$url" | sed -n -e 's/.*<title>\(.*\)<\/title>.*/\1/p;' )
    title=$title

    echo "Date: $time"
    echo "URL: $url"
    echo "Title: $title"
    read -e -p "Tags (space-separated): " tags
    read -e -p "Description: " desc

    tmp=/tmp/bm-$$
    echo -e "$time\t$url\t$tags\t$title\t$desc" | cat - $FILE > $tmp
    mv $tmp $FILE
    rm -f $tmp

    read -n 1 -p "Edit bookmarks file? [y/N]: " yesno
    if  [ "$yesno" == "y" ]; then
        edit
    fi
}

edit() {
    $EDITOR $FILE
}

search() {
    grep $1 $FILE | \
        awk -F"\t" '{ printf("%s\n%s\n", $4, $2);
                printf("[%s] %s\n\n", strftime("%Y-%m-%d", $1), $3); }' | \
        less
}

publish() {
    echo "title: Assorted Links"
    echo "created: March 30, 2010 00:22 EDT"
    echo "modified: " $(date +"%B %d, %Y %H:%M:%S %Z")
    echo "markup: xhtml"
    echo ""
    echo "<p>"
    echo "Below are some links which I found useful or interesting at some point."
    echo "This page is my decidedly anti-social, simplified alternative to the new"
    echo "wave of social bookmarking sites.  Instead, these links are stored in a"
    echo "plain text file and processed using a simple"
    echo "<a href=\"/git/scripts.git/plain/bm\">shell script</a>."
    echo "</p>"
    echo ""
    echo "<dl>"
    cat $FILE | \
        sed -e 's/&/\&amp;/g' | \
        sed -e 's/</\&lt;/g' | \
        sed -e 's/>/\&gt;/g' | \
        awk -F"\t" '{
            printf("  <dt><a href=\"%s\" rel=\"nofollow\">%s</a>", $2, $4);
            printf(" <span class=\"meta\">(%s %s)</span></dt>\n",
                   strftime("%Y-%m-%d", $1), $3);
            if ($5) printf("  <dd>%s </dd>\n", $5);
            printf("\n"); }'
    echo "</dl>"
    echo "<p class=\"meta\">Top tags:"
    cat $FILE | awk -F"\t" '{ print $3 }' | sed 's/ /\n/g' | sort | uniq -c | sort -n -r | head -n 25
    echo "</p>"
}

case "$1" in
    add)
        add $2
	;;
    edit)
        edit
	;;
    search)
        search $2
	;;
    publish)
        publish > $OUTPUT
	;;
    *)
	usage
	;;
esac

exit 0
