#!/bin/bash
# https://tex.stackexchange.com/questions/1325/using-latexdiff-with-git
TMPDIR=$(mktemp -d /tmp/git-latexdiff.XXXXXX)
latexdiff "$1" "$2" > $TMPDIR/diff.tex
pdflatex -interaction nonstopmode -output-directory $TMPDIR $TMPDIR/diff.tex
open -W $TMPDIR/diff.pdf
trap $(rm -rf $TMPDIR) EXIT
