#!/bin/bash
#
# LaTeXbot
#
# Read each line of $PATH_FILE and process it accordingly.  If the
# line is a directory, call the $LATEX command on each file in the
# directory matching the glob *.tex that changed since the last run.
# If the line is a path to a single .tex file, we assume it is the
# master tex file for a project in the directory (e.g., a book).  Call
# $LATEX on that file if any other .tex file in the directory changed
# since the last run.  This script is designed to be called from a
# cron job as often as needed.

PATH_FILE="$HOME/.latexbot"
TIMESTAMP_FILE="$HOME/.latexbot-timestamp"
LATEX="pdflatex -interaction=nonstopmode"

while read path; do
    if [ -d "$path" ]; then
        cd $path
        for file in *.tex; do
            if [ "$file" -nt $TIMESTAMP_FILE ]; then
                $LATEX "$file"
            fi
        done
    elif [ -f "$path" ]; then
        dir=$(dirname $path)
        file=$(basename $path)
        cd $dir
        for other in *.tex; do
            if [ "$other" -nt $TIMESTAMP_FILE ]; then
                $LATEX "$file"
                break
            fi
        done
    fi
done < $PATH_FILE
touch $TIMESTAMP_FILE
