#!/bin/sh
#
# Starts and stops the matlab license manager.
#
# Jason Blevins <jrblevin@sdf.lonestar.org>
# Durham, August 6, 2004

MATLABDIR=/usr/local/matlab7
MATLABUSER=jrblevin

RETVAL=0

start() {
    echo -n "matlab: Starting license daemon: "
    $MATLABDIR/etc/lmstart -u $MATLABUSER >& /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	echo "done."
	touch /var/lock/matlablm
    else
	echo "failed."
    fi
 
    return $RETVAL
}

stop() {
    echo -n "matlab: Stopping license daemon: "
    $MATLABDIR/etc/lmdown >& /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	echo "done."
	rm -f /var/lock/matlablm
    else
	echo "failed."
    fi

    return $RETVAL
}

status() {
    $MATLABDIR/etc/lmstat
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
	;;
  restart)
        stop
        start
	;;
  force-reload)
  	stop
	start
	;;
  *)
	echo "Usage: matlablm {start|stop|status|restart|force-reload}"
	exit 1
esac
exit $RETVAL

