#!/bin/sh

TMP=/tmp/mdprint-$$.pdf
PREAMBLE=$HOME/config/app/pandoc/preamble.tex
LPOPTIONS="-o Duplex=DuplexNoTumble -o PreFilter=No"

rm -f $TMP
markdown2pdf -H $PREAMBLE -o $TMP $1
pdftops $TMP - | lpr $LPOPTIONS
rm -f $TMP
