#!/bin/sh

TMP=/tmp/mdprint-$$.pdf
PREAMBLE=$HOME/config/app/pandoc/preamble.tex
LPOPTIONS="-o sides=two-sided-long-edge"

rm -f $TMP

if [[ -n "$1" ]] ; then
    markdown2pdf -H $PREAMBLE -o $TMP $1
else
    cat | markdown2pdf -H $PREAMBLE -o $TMP
fi

pdftops $TMP - | lpr $LPOPTIONS

rm -f $TMP
