#!/bin/bash
#
# modlogger.sh -- logs songs played by mpd to a tab-delimited text file
#
# Copyright (C) 2010 Jason R. Blevins
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the three-clause BSD license.
#
# Dependencies: mpd, mpc, and grep.

# Configuration
host=127.0.0.1
port=6600

# Output filename
if [[ -n $MPDLOGGER_FILE ]]; then
    file=$MPDLOGGER_FILE
else
    file=$HOME/.playlist.txt
fi

# Poll interval in seconds
if [[ -n $MPDLOGGER_INTERVAL ]]; then
    interval=$MPDLOGGER_INTERVAL
else
    interval=60
fi

# Previously playing song
previous=$RANDOM

# Set MPD environment variables
export MPD_HOST=$host
export MPD_PORT=$port

while true
do
    current=$(mpc --format "\t%title%\t%artist%\t%album%" | grep "^	")
    if [ -n "$current" ]; then
        if [ "$current" != "$previous" ]; then
            echo $(date +%s) "$current" >> $file
            previous="$current"
        fi
    fi
    sleep $interval
done
