#!/bin/bash
#
# Downloads and installs the latest Firefox nightly build.  This script
# is designed to be executed daily by root, for example, from
# /etc/cron.d/daily/.
#
# Copyright (C) 2010 Jason R. Blevins
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS `AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# Nightly snapshot URL
url=http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/

# Temporary file
tmp=/tmp/upgrade-firefox-$$.html

# Automatically detect system architecture
arch=`uname -m`

# Retrieve index and determine build version
wget -q -c -O $tmp $url
latest=$(grep "en-US.linux-$arch.tar.bz2" $tmp | \
    tail -n 1 | \
    sed 's!.*<a href="\(.*\.en-US\.linux.*\.tar\.bz2\)">.*!\1!')
rm $tmp

# Download tarball
echo "Fetching latest build: $latest"
tarball=/tmp/$latest
wget -c -O $tarball $url$latest

# Install new version
echo "Installing in /opt/firefox..."
rm -rf /opt/firefox
tar -C /opt -jxvf $tarball

# Clean up
rm -f $tarball
